// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWez-Gg-tVanQgGPfG0uLxOw9yL0mSB1M',
    appId: '1:483571173321:web:038907d2c0c5889ad3ca18',
    messagingSenderId: '483571173321',
    projectId: 'pedidosalaorden-bc075',
    authDomain: 'pedidosalaorden-bc075.firebaseapp.com',
    storageBucket: 'pedidosalaorden-bc075.appspot.com',
    measurementId: 'G-7NRWH30KJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqKffUesXRGCstR-_L5Yj-RKvvyMHzJk',
    appId: '1:483571173321:android:4bb0295f2402feafd3ca18',
    messagingSenderId: '483571173321',
    projectId: 'pedidosalaorden-bc075',
    storageBucket: 'pedidosalaorden-bc075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_McJuQ4D1jTYZn5Iie89NdU7wMtGXm0',
    appId: '1:483571173321:ios:928eb4229487860cd3ca18',
    messagingSenderId: '483571173321',
    projectId: 'pedidosalaorden-bc075',
    storageBucket: 'pedidosalaorden-bc075.appspot.com',
    iosBundleId: 'com.example.pedidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd_McJuQ4D1jTYZn5Iie89NdU7wMtGXm0',
    appId: '1:483571173321:ios:2de69718cf999cd2d3ca18',
    messagingSenderId: '483571173321',
    projectId: 'pedidosalaorden-bc075',
    storageBucket: 'pedidosalaorden-bc075.appspot.com',
    iosBundleId: 'com.example.pedidos.RunnerTests',
  );
}
